# Generated by Django 4.1.7 on 2023-04-18 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='search_fields',
            field=models.CharField(default='', max_length=50),
        ),
    ]
