# Generated by Django 4.1.7 on 2023-03-31 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_room_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='user',
        ),
    ]
