# Generated by Django 4.1.7 on 2023-04-01 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatroom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='username',
            field=models.CharField(default='anonymous', max_length=50),
        ),
    ]
