# Generated by Django 4.1.7 on 2023-04-01 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatroom', '0002_chatroom_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='channel_name',
            field=models.CharField(default='', max_length=20),
        ),
    ]
